# Generated by Django 6.0.3 on 2026-04-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('accent', models.CharField(default='amber', max_length=30)),
                ('movies', models.ManyToManyField(blank=True, related_name='collections', to='api.movie')),
            ],
        ),
    ]
